### ISSUE TITLE
Tag 0.2 isn't valid in semver

### ISSUE THREAD

**Issue by garyb** [zudov/purescript-strongcheck-generics#2]
Sorry, looks like bower doesn't like that. Can you rename it as `v0.2.0` instead? Thanks!

**Comment by zudov** [comment]
Oh, absolutely forgot about that. Will fix in a moment.

**Comment by zudov** [comment]
@garyb Fixed. `bower install purescript-strongcheck-generics#0.2.0` works fine now.

**Comment by zudov** [comment]
I'll also upload it to pursuit.

**Comment by garyb** [comment]
Thanks!
